language: php

php:
  - 5.6
  - 7.0

before_script:
  - travis_retry composer self-update --no-progress -n
  - travis_retry composer install -n --prefer-dist

script:
  # Find php syntax errors
  - php -l src
  - php -l tests

  # Run unit tests
  - phpunit --coverage-text --coverage-clover=coverage.clover

  # Check for coding standard violations
  - vendor/bin/phpcs --standard=PSR2 --ignore=Wsdl src tests

notifications:
  email:
    on_success: never